### ISSUE TITLE
Lecture du site

### ISSUE THREAD

**Issue by MaximeKlekowicki** [IFATech-Metz/dev-log-7#10]
Le site manque un peu de visibilité, la lecture des données du site sont un peu compliqué

**Comment by OuassilaD** [comment]
A l'affichage de la page, il n'existe aucune ambiguïté pour comprendre qu'il s'agit de données météo sur une période de 5 jours à une heure bien spécifique, on anticipe les prévisions sans avoir à cliquer sur un multitude de boutons et checkbox!
