### ISSUE TITLE
Lecture du site

### ISSUE THREAD

**Issue by FlowerSushi** [IFATech-Metz/dev-log-7#11]
Lors d'une requête météo, l'icone de la meteo actuelle prend toute la taille de l'écran, et un nombre s'affiche en haut à gauche,  sans que l'on ne sache à quoi il correspond.
Aussi, à l'initiation de la page, l'adresse "http://api.openweathermap.org/data/2.5/weather?q=Metz&units=metric&appid=dd8984d9d3055c049aa688cc2dc715b7" apparait

**Comment by arsiak** [comment]
- J'ai re-testé et l'icône ne prend pas toute la page
- L'affichage de l'adresse en cochant la case correspond à une fonctionnalité développée par le prof en cours
