### ISSUE TITLE
corrections

### ISSUE THREAD

**Issue by Antopablo** [IFATech-Metz/dev-log-7#14]
Dans la page Essai.html, une faute à "Accueil".

Je pense qu'il y a un problème sur la température maximum/minimum dans les prévisions, elle est égale à la température prévisionnelle

Sur on appuis plusieurs fois sur le bouton "chercher" dans la page Essai.html, il y à un rectangle d'info à chaque fois.

**Comment by OuassilaD** [comment]
1. "Accueil" une faute de frappe 
2. Concernant le bouton "chercher" le maintien des critères dans les champs sur la page prévisions du jour fait que le résultat est lié à ces critères de filtre:  le résultat respecte correctement la saisie dans les champs de recherche 
3. les températures min et max sont extraites pour une heure donnée, donc forcément elle sont égales dans les prévisions et varie pour la journée en cours  car c'est par rapport à une amplitude de 24h
