### ISSUE TITLE
URL hidden ? 

### ISSUE THREAD

**Issue by Chaussettecin** [IFATech-Metz/dev-log-7#18]
URL qui s'affiche 
http://api.openweathermap.org/data/2.5/weather?q=Metz&units=metric&appid=dd8984d9d3055c049aa688cc2dc715b7
A cause de l'api et la check box.

Possibilité de le mettre en hidden. 

Pourquoi le lien Afficher toutes les informations... rédige vers un lien pub?

format de la date pas très ergonomique ?

**Comment by arsiak** [comment]
- On peut cacher l'URL avec la petite checkbox
- Le lien "afficher toutes les informations" redirige vers une page .html que l'on a développé.
- C'est noté, nous allons améliorer le formatage de la date
